//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusiness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBusiness()
        {
            this.tblSaloonAppointments = new HashSet<tblSaloonAppointment>();
        }
    
        public System.Guid BusinessGuid { get; set; }
        public string BusinessName { get; set; }
        public System.Guid BusinessTypeGuid { get; set; }
        public string PNumber { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.Guid CityGuid { get; set; }
        public string PinCode { get; set; }
        public string BusinessImage { get; set; }
        public System.Guid CountryGuid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedByGuid { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.Guid> DeletedByGuid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.Guid ManagerUserGuid { get; set; }
        public string Description { get; set; }
        public string OrderTiming { get; set; }
        public string PickUpTiming { get; set; }
        public string ServiceCharge { get; set; }
        public string ServiceTax { get; set; }
        public string FlatRate { get; set; }
        public string RateAfterKm { get; set; }
    
        public virtual tblBusinessType tblBusinessType { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaloonAppointment> tblSaloonAppointments { get; set; }
    }
}
