//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCountry()
        {
            this.tblRestaurants = new HashSet<tblRestaurant>();
        }
    
        public string CountryDisplayName { get; set; }
        public string CountryName { get; set; }
        public System.Guid CountryGUID { get; set; }
        public System.DateTime DateModified { get; set; }
        public string PhoneCode { get; set; }
        public string ISOCountryCode { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string CountryTwoLetterCode { get; set; }
        public string CountryThreeLetterCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRestaurant> tblRestaurants { get; set; }
    }
}
