//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomProperty
    {
        public System.Guid CustomPropertyGuid { get; set; }
        public System.Guid LocationGuid { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
    }
}
