//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public System.Guid ItemGuid { get; set; }
        public string ItemName { get; set; }
        public Nullable<System.Guid> CategoryGuid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedByGuid { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeletedByGuid { get; set; }
    
        public virtual tblLookUpDomainValue tblLookUpDomainValue { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
