//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookUpDomain
    {
        public System.Guid LookDomainGuid { get; set; }
        public string LookUpDomainCode { get; set; }
        public string LookUpDomainDescription { get; set; }
    }
}
