//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookUpDomain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLookUpDomain()
        {
            this.tblLookUpDomainValues = new HashSet<tblLookUpDomainValue>();
        }
    
        public System.Guid LookUpDomainGuid { get; set; }
        public string LookUpDomainCode { get; set; }
        public string LookUpDomainDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLookUpDomainValue> tblLookUpDomainValues { get; set; }
    }
}
