//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public System.Guid OrderItemGuid { get; set; }
        public System.Guid FK_OrderGuid { get; set; }
        public System.Guid FK_ItemGuid { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public System.Guid FK_CreatedByGuid { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
