//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bringly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaloonTimeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaloonTimeMaster()
        {
            this.tblSaloonAppointments = new HashSet<tblSaloonAppointment>();
        }
    
        public System.Guid SaloonTimeGuid { get; set; }
        public string SlotTime { get; set; }
        public System.Guid FK_CreatedByGuid { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaloonAppointment> tblSaloonAppointments { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
